# Generated by Django 5.0.3 on 2024-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cif', models.CharField(max_length=33, null=True, unique=True)),
                ('email', models.CharField(max_length=111, null=True, unique=True)),
                ('password', models.CharField(max_length=111, null=True)),
                ('tlf', models.CharField(max_length=33, null=True)),
                ('tlf2', models.CharField(max_length=33, null=True)),
                ('numvisit', models.BigIntegerField(default=0)),
                ('regtime', models.CharField(max_length=33, null=True)),
                ('lastvisit', models.CharField(max_length=33, null=True)),
                ('state', models.CharField(max_length=22, null=True)),
                ('uid', models.CharField(max_length=111, null=True)),
                ('address', models.CharField(max_length=111, null=True)),
                ('zipcode', models.CharField(max_length=22, null=True)),
                ('province', models.CharField(max_length=11, null=True)),
                ('country', models.CharField(max_length=22, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_com_id_3a34d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=33, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_cou_id_4994ef_idx')],
            },
        ),
    ]
