# Generated by Django 5.0.3 on 2024-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cif', models.CharField(max_length=33)),
                ('email', models.CharField(max_length=111)),
                ('tlf', models.CharField(max_length=33)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_com_id_3a34d1_idx'), models.Index(fields=['cif'], name='invoice_com_cif_4d75d8_idx')],
            },
        ),
    ]
