# Generated by Django 5.1 on 2024-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicledata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.BigIntegerField(null=True)),
                ('company_id', models.BigIntegerField(null=True)),
                ('customer_id', models.BigIntegerField(null=True)),
                ('matricula', models.CharField(max_length=11, null=True)),
                ('color', models.CharField(max_length=22, null=True)),
                ('km', models.PositiveIntegerField(null=True)),
                ('marca', models.CharField(max_length=111, null=True)),
                ('modelo', models.CharField(max_length=111, null=True)),
                ('chassis_number', models.CharField(max_length=111, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.BigIntegerField(null=True)),
                ('usenum', models.BigIntegerField(null=True)),
                ('code', models.CharField(max_length=41, null=True, unique=True)),
                ('description', models.CharField(max_length=111, null=True, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id'], name='invoice_art_company_5faba9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=111, null=True)),
                ('cif', models.CharField(max_length=33, null=True, unique=True)),
                ('email', models.CharField(max_length=111, null=True, unique=True)),
                ('emailcliente', models.CharField(max_length=111, null=True)),
                ('password', models.CharField(max_length=111, null=True)),
                ('tlf', models.CharField(max_length=33, null=True)),
                ('tlf2', models.CharField(max_length=33, null=True)),
                ('numvisit', models.BigIntegerField(default=0)),
                ('regtime', models.CharField(max_length=33, null=True)),
                ('lastvisit', models.CharField(max_length=33, null=True)),
                ('state', models.CharField(max_length=22, null=True)),
                ('uid', models.CharField(max_length=111, null=True)),
                ('country', models.CharField(max_length=33, null=True)),
                ('province', models.CharField(max_length=33, null=True)),
                ('zipcode', models.CharField(max_length=22, null=True)),
                ('city', models.CharField(max_length=33, null=True)),
                ('address', models.CharField(max_length=111, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_com_id_3a34d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=33, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_cou_id_4994ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.BigIntegerField(null=True)),
                ('usednum', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('cif_nif', models.CharField(max_length=33, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=11, null=True)),
                ('city', models.CharField(max_length=111, null=True)),
                ('province', models.CharField(max_length=111, null=True)),
                ('country', models.CharField(default='España', max_length=111)),
                ('phone', models.CharField(max_length=33, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id'], name='invoice_cus_company_746230_idx')],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(null=True, unique=True)),
                ('serie', models.CharField(max_length=33, null=True)),
                ('nombre_cliente', models.CharField(max_length=111, null=True)),
                ('cif', models.CharField(max_length=33, null=True)),
                ('ejercicio', models.CharField(max_length=11, null=True)),
                ('company_id', models.BigIntegerField(null=True)),
                ('fecha', models.CharField(max_length=33, null=True)),
                ('vencimiento', models.CharField(max_length=33, null=True)),
                ('forma_pago', models.CharField(default='CONTADO', max_length=111)),
                ('baseimponible1', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('baseimponible2', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('baseimponible3', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('baseimponible4', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('baseimponible5', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('iva1', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('iva2', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('iva3', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('iva4', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('iva5', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importeiva1', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importeiva2', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importeiva3', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importeiva4', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importeiva5', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('totaliva', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('recargo1', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('recargo2', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('recargo3', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('recargo4', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('recargo5', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importerecargo1', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importerecargo2', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importerecargo3', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importerecargo4', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('importerecargo5', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('totalivarecargo', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('labour_hours', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id'], name='invoice_fac_company_4740b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facturalineas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.BigIntegerField(null=True)),
                ('company_id', models.BigIntegerField(null=True)),
                ('article_id', models.BigIntegerField(null=True)),
                ('article_name', models.CharField(max_length=111, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id'], name='invoice_fac_company_a58809_idx'), models.Index(fields=['invoice_id'], name='invoice_fac_invoice_c8e056_idx')],
            },
        ),
    ]
