# Generated by Django 5.0.3 on 2024-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='remarks',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
