# Generated by Django 5.0.3 on 2024-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='passw',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cif',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tlf',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
