# Generated by Django 5.0.3 on 2024-08-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='uid',
        ),
    ]
