# Generated by Django 5.1 on 2024-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=111, null=True, unique=True),
        ),
    ]
