# Generated by Django 5.0.3 on 2024-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='importe_ivas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
