# Generated by Django 5.1 on 2024-08-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_company_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code',
        ),
    ]
