# Generated by Django 5.0.3 on 2024-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_company_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uid',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
