# Generated by Django 5.1 on 2024-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='emailcliente',
            field=models.CharField(max_length=111, null=True, unique=True),
        ),
    ]
