# Generated by Django 5.1 on 2024-09-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_factura_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='serie_fact_unique',
            field=models.CharField(max_length=22, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie_fact',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
