# Generated by Django 5.0.3 on 2024-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_factura_importe_ivas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='baseimponible1',
            new_name='total2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='baseimponible2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='baseimponible3',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='baseimponible4',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='baseimponible5',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importeiva1',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importeiva2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importeiva3',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importeiva4',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importeiva5',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importerecargo1',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importerecargo2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importerecargo3',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importerecargo4',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='importerecargo5',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva1',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva3',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva4',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva5',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='recargo1',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='recargo2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='recargo3',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='recargo4',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='recargo5',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='totaliva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='totalivarecargo',
        ),
        migrations.AddField(
            model_name='factura',
            name='ivas_desglose',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
