# Generated by Django 5.0.3 on 2024-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_factura_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='comment_ret_rec',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
