# Generated by Django 5.0.3 on 2024-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_company_address_company_country_company_passw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='passw',
            new_name='password',
        ),
        migrations.AddField(
            model_name='company',
            name='lastvisit',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='numvisit',
            field=models.BigIntegerField(null=True),
        ),
    ]
