# Generated by Django 5.0.3 on 2024-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_company_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cif', models.CharField(max_length=33, null=True, unique=True)),
                ('exercise', models.CharField(max_length=11, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_fac_id_636928_idx')],
            },
        ),
    ]
