# Generated by Django 5.1 on 2025-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_factura_name_factura_alter_factura_apunta_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, default='', max_length=111, unique=True),
        ),
    ]
