# Generated by Django 5.1 on 2024-09-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_factura_serie_fact_unique_alter_factura_serie_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='serie',
        ),
    ]
