# Generated by Django 5.0.3 on 2024-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_passw_company_password_company_lastvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
