# Generated by Django 5.1 on 2024-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_company_emailcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='province',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
