# Generated by Django 5.0.3 on 2024-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_factura_comment_ret_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ejercicio',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
