# Generated by Django 5.0.3 on 2024-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_baseimponible1_factura_total2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='apunta_factura',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
