# Generated by Django 5.0.3 on 2024-08-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=111, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='invoice_art_name_712290_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cif', models.CharField(max_length=33, null=True, unique=True)),
                ('name', models.CharField(max_length=111, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cif'], name='invoice_cus_cif_1dbbfa_idx'), models.Index(fields=['name'], name='invoice_cus_name_3da24d_idx')],
            },
        ),
    ]
