# Generated by Django 5.1 on 2024-09-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_factura_ejercicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='usenum',
            new_name='usednum',
        ),
    ]
