# Generated by Django 5.1 on 2024-09-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_factura_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
