# Generated by Django 5.0.3 on 2024-08-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_company_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='invoice_com_cif_4d75d8_idx',
        ),
    ]
