# Generated by Django 5.0.3 on 2024-09-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_factura_apunta_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturalineas',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='facturalineas',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='facturalineas',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='article_num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='iva_porcent',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='iva_type',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
