# Generated by Django 5.1 on 2024-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_company_city_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
