# Generated by Django 5.1 on 2024-09-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_factura_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='comment_ret_rec',
            new_name='commentario',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='remarks',
            new_name='observacion',
        ),
    ]
