# Generated by Django 5.1 on 2024-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artcode',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
