# Generated by Django 5.0.3 on 2024-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_facturalineas_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='facturalineas',
            name='article_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
