# Generated by Django 5.0.3 on 2024-09-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_rename_usenum_article_usednum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='usednum',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='usednum',
        ),
    ]
