# Generated by Django 5.0.3 on 2024-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_article_customer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='invoice_art_name_712290_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='invoice_cus_cif_1dbbfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='invoice_cus_name_3da24d_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='invoice_fac_id_636928_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='company_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='company_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['company_id'], name='invoice_art_company_5faba9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_id'], name='invoice_cus_company_746230_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['company_id'], name='invoice_fac_company_4740b3_idx'),
        ),
    ]
