# Generated by Django 5.0.3 on 2024-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_company_invoice_com_cif_4d75d8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cif',
            field=models.CharField(max_length=33, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=111, null=True, unique=True),
        ),
    ]
