# Generated by Django 5.1 on 2024-08-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_company_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='price_hour',
        ),
    ]
