# Generated by Django 5.0.3 on 2024-08-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_company_cif_alter_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=33, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['id'], name='invoice_cou_id_4994ef_idx'),
        ),
    ]
