# Generated by Django 5.1 on 2024-08-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_company_price_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='emailcliente',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
