# Generated by Django 5.1 on 2024-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_article_artcode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='invoice_doc_id_f3c779_idx',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='nombre',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='valor',
            new_name='value',
        ),
        migrations.AddField(
            model_name='document',
            name='company_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['description'], name='invoice_doc_descrip_02ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company_id'], name='invoice_doc_company_677429_idx'),
        ),
    ]
