# Generated by Django 5.0.3 on 2024-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturalineas',
            name='serie',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
