# Generated by Django 5.1 on 2024-09-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_rename_comment_ret_rec_factura_commentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='commentario',
            new_name='comentario',
        ),
    ]
