# Generated by Django 5.0.3 on 2024-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_facturalineas_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='base_imponible',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_address',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_cif',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_city',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_company_name',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_pais',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_person_name',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_provice',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emisor_zip_code',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_efecto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_address',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_cif',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_city',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_company_name',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_pais',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_person_name',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='receptor_zip_code',
        ),
        migrations.AddField(
            model_name='factura',
            name='customer_num',
            field=models.BigIntegerField(null=True),
        ),
    ]
