# Generated by Django 5.1 on 2024-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_commentario_factura_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='emisor_provice',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
