# Generated by Django 5.1 on 2024-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_document_invoice_doc_id_f3c779_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='clientcode',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
