# Generated by Django 5.0.3 on 2024-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_article_usenum_customer_usenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicledata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.BigIntegerField(null=True)),
                ('company_id', models.BigIntegerField(null=True)),
                ('customer_id', models.BigIntegerField(null=True)),
                ('registration', models.CharField(max_length=11, null=True)),
                ('colour', models.CharField(max_length=22, null=True)),
                ('kilometres', models.PositiveIntegerField(null=True)),
                ('make', models.CharField(max_length=111, null=True)),
                ('model', models.CharField(max_length=111, null=True)),
                ('chassis_number', models.CharField(max_length=111, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cif',
            new_name='cif_nif',
        ),
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.CharField(max_length=41, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='España', max_length=111),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='commercial_name',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='expiration',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='payment_form',
            field=models.CharField(default='CONTADO', max_length=111),
        ),
        migrations.AddField(
            model_name='factura',
            name='serie',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cif',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
