# Generated by Django 5.0.3 on 2024-09-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_factura_base_imponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='receptor_company_name',
            field=models.CharField(max_length=222, null=True, unique=True),
        ),
    ]
