# Generated by Django 5.0.3 on 2024-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(max_length=33, null=True, unique=True),
        ),
    ]
