# Generated by Django 5.1 on 2024-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_factura_emisor_provice'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
