# Generated by Django 5.1 on 2024-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_customer_clientcode_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cif_nif'], name='invoice_cus_cif_nif_720b7b_idx'),
        ),
    ]
