# Generated by Django 5.0.3 on 2024-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_country_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hascode',
            field=models.CharField(max_length=111, null=True),
        ),
    ]
