# Generated by Django 5.0.3 on 2024-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_vehicledata_rename_name_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_hour',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='labour_hours',
            field=models.DecimalField(decimal_places=1, max_digits=11, null=True),
        ),
    ]
