# Generated by Django 5.1 on 2024-09-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_factura_precio_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='labour_hours',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='precio_hora',
        ),
    ]
