# Generated by Django 5.0.3 on 2024-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_factura_receptor_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='receptor_company_name',
            field=models.CharField(max_length=222, null=True),
        ),
    ]
