# Generated by Django 5.1 on 2024-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['id'], name='invoice_art_id_c82ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['description'], name='invoice_art_descrip_b92c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id'], name='invoice_cus_id_a48e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['id'], name='invoice_fac_id_636928_idx'),
        ),
    ]
