# Generated by Django 5.1 on 2024-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_factura_receptor_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledata',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='km',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='modelo',
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='other_data',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='matricula',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
