# Generated by Django 5.1 on 2024-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_remove_vehicledata_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ivas_desglose',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
