# Generated by Django 5.0.3 on 2024-08-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoiceline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoiceline',
            new_name='Facturalineas',
        ),
        migrations.RenameIndex(
            model_name='facturalineas',
            new_name='invoice_fac_company_a58809_idx',
            old_name='invoice_inv_company_ecdc24_idx',
        ),
        migrations.RenameIndex(
            model_name='facturalineas',
            new_name='invoice_fac_invoice_c8e056_idx',
            old_name='invoice_inv_invoice_166710_idx',
        ),
    ]
