# Generated by Django 5.1 on 2024-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_factura_ivas_desglose'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='vehicle_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
