# Generated by Django 5.1 on 2024-09-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_factura_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='vehicle_id',
        ),
    ]
