# Generated by Django 5.0.3 on 2024-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_rename_exercise_factura_ejercicio_factura_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledata',
            old_name='colour',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='vehicledata',
            old_name='kilometres',
            new_name='km',
        ),
        migrations.RenameField(
            model_name='vehicledata',
            old_name='make',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehicledata',
            old_name='registration',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='vehicledata',
            old_name='model',
            new_name='modelo',
        ),
    ]
