# Generated by Django 5.1 on 2024-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_remove_factura_vehicle_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicledata',
            index=models.Index(fields=['invoice_id'], name='invoice_veh_invoice_367b29_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledata',
            index=models.Index(fields=['company_id'], name='invoice_veh_company_c6af3d_idx'),
        ),
    ]
