# Generated by Django 5.0.3 on 2024-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_rename_colour_vehicledata_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='usenum',
            new_name='usednum',
        ),
    ]
