# Generated by Django 5.1 on 2024-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_remove_vehicledata_invoice_veh_company_c6af3d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturalineas',
            name='descuento_val',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='importe_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='importe_con_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='importe_res',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='iva_valor',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
